ci(validation): add validation gate
- Validation gate aggregates results of all the runs and rolls
  them up to success if every one of them succeeded, otherwise
  it fails. This gate is used in Github's branch protection rules.

diff --git a/.github/workflows/validation.yaml b/.github/workflows/validation.yaml
--- a/.github/workflows/validation.yaml
+++ b/.github/workflows/validation.yaml
@@ -34,3 +34,16 @@ jobs:
     permissions:
       contents: read
       security-events: write
+
+  validation-gate:
+    name: Validation
+    runs-on: ubuntu-latest
+    needs: validate
+    if: always()
+    steps:
+      - name: Check matrix result
+        run: |
+          if [ "${{ needs.validate.result }}" != "success" ]; then
+            echo "One or more stacks failed validation"
+            exit 1
+          fi
